### ISSUE TITLE
How you are getting data to produce accumulated precipitation ?

### ISSUE THREAD

**Issue by masterwayne** [fmidev/himan#1]
I wanted to know from where you are getting data to generate accumulated precipitation.

**Comment by tackandr** [comment]
http://bfy.tw/ItxQ

**Comment by mpartio** [comment]
Precipitation data is generated by the forecast model. FMI is providing two forecasts free of charge, for more information please see:

https://en.ilmatieteenlaitos.fi/open-data

**Comment by masterwayne** [comment]
I am using this for precipation data : http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl?dir=%2Fgfs.2018070500

Do u know how to map data points to latitude and longitude for fetching information regarding precipitation at any particular latitude and longitude ?

**Comment by mpartio** [comment]
Reading a single point of data from a grib is not something you need Himan for, hence I think this issue is not relevant.

For your reference, you can read grib files with for example eccodes library from ECMWF (https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home)

Example, reading data for latitude=60,longitude=25:
```
$ grib_ls -l 60,25 gfs.t00z.pgrb2.1p00.f003 
gfs.t00z.pgrb2.1p00.f003
edition      centre       date         dataType     gridType     typeOfLevel  level        stepRange    shortName    packingType         value1  value2  value3  value4 
2            kwbc         20180705     fc           regular_ll   surface      0            0-3          prate        grid_complex_spatial_differencing  0 3.4e-05 0 0.000114 
1 of 1 messages in gfs.t00z.pgrb2.1p00.f003

1 of 1 total messages in 1 files
Input Point: latitude=60.00  longitude=25.00
Grid Point chosen #2 index=10825 latitude=60.00 longitude=25.00 distance=0.00 (Km)
Other grid Points
- 1 - index=10826 latitude=60.00 longitude=26.00 distance=55.60 (Km)
- 2 - index=10825 latitude=60.00 longitude=25.00 distance=0.00 (Km)
- 3 - index=10466 latitude=61.00 longitude=26.00 distance=123.95 (Km)
- 4 - index=10465 latitude=61.00 longitude=25.00 distance=111.20 (Km)
```
