### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by fox91** [fmidev/himan#5]
Hi,
I'm trying to run the example code but I'm not able due to the missing radon database.
How can I create one? I'm not able to find the schema in this repo.

```
Info::radon Connected to radon (db=postgres, host=172.17.0.2:5432)
Fatal::himan ERROR:  relation "fmi_producer" does not exist
LINE 1: ... f.id, f.name, f.class_id, g.centre, g.ident FROM fmi_produc...
                                                             ^
```

Thanks

**Comment by mpartio** [comment]
Should work now with https://github.com/fmidev/himan/commit/2638410904c2f004c1fd0ec61cf64aff2924b20a

Radon database schema is in a different repo here: https://github.com/fmidev/radon.git

This no-database mode (which the example is running) was implemented _before_ radon database schema was open sourced... it's not really used much by us hence the bug.

Might be worthwhile now to write another example that includes radon database -> #6
